name = "DrivingTime"
uuid = "1ecbb15d-b281-4057-aa90-5b0af5572765"
version = "0.0.2"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IniFile = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RouteSlopeDistance = "07025e9e-5a27-4179-b043-88080b1ee239"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Dates = "1.11.0"
IniFile = "0.5.1"
Interpolations = "0.16.2"
OrdinaryDiffEq = "6.105.0"
OrdinaryDiffEqCore = "2.3.0"
Plots = "1.41.3"
SciMLBase = "2.132.0"
